
name: azure-actions-repo-stack
description: This is a stack that can be used by someone who wants to start authoring a brand new GitHub Action targetting Azure.
branding:
  icon: 'Azure.svg'
  color: 'blue'
inputs:
 - name: Reviewer_Count
   default: 2
   description: Number of required reviewers for PR
   validvalues: 
   - 2
   - 3
   - 4
   - 5
   - 6
#-------------------------------------------------------------

configs:
# Meta data for creating the new repository
- repo-metadata:
    parameters:
      description: This is a Azure GitHub Action
      topics:
      - Azure
      - Action

 # Branch protection rules
- branches:
   - name: releases/*
     parameters:
       require-code-owner-reviews: true
       required-approving-review-count: {{ inputs.Reviewer_Count }}
   
   - name: main
     parameters:
       require-code-owner-reviews: true
       required-approving-review-count: {{ inputs.Reviewer_Count }}
            
- security:
    parameters: 
      vulnerability-alerts: false
      automated-security-fixes: false

#-------------------------------------------------------------
# Initialization workflow to run
# init:
# #This workflow file will NOT be part of the stack (new repo created). 
# # workflow could use the stack inputs using the notation : ${{ github.event.inputs.name }}
#  - uses: ".github/workflows/setup.yml"

# # This section will be enhanced to define other Stack operations: up, build, deploy etc.

# github-apps:
# - slug: Azure
#   parameters:
#      environment: production
#      secrets:
#        - name: Azure_SPN_ID
#        - name: Azure_Tenant_ID

# - slug: codetree
